### ISSUE TITLE
Toolchain

### ISSUE THREAD

**Issue by jadonk** [statropy/msp430F55xx_usb_uart_bridge#1]
Can you utilize an open source toolchain for the build? I believe GCC has MSP430 support: https://gcc.gnu.org/onlinedocs/gcc/MSP430-Options.html.

**Comment by statropy** [comment]
https://www.ti.com/tool/MSP430-GCC-OPENSOURCE

I had to make a new project with the GNU compiler because just switching broke CCS. TI does give a code size difference warning, and switching to this compiler added 2004 bytes to the code section, a 21% increase. There may be some further optimizations possible, which I'll check on.

I'll also look at exporting from CCS to a make system. I would like to add a CI configuration for this.
